SELECT
    upper(PLATFORM) AS PLATFORM,
    upper(REGION) AS REGION,
    upper(PRODUCT_CODE) AS PRODUCT_ID,
    upper(SELLER_SKU) AS SKU_ID,
    PRODUCT_TITLE AS PRODUCT_NAME,
    SELLER_NAME AS SHOP_NAME,
    CATEGORY_NAME AS CATEGORY,
    BRAND_NAME AS BRAND,
    SELLING_PRICE AS PRICE,
    INVENTORY AS STOCK,
    REVIEW_SCORE AS RATING,
    UNITS_SOLD,
    CONCAT_WS(
        '_',
        UPPER(REGION),
        UPPER(PRODUCT_ID),
        UPPER(SKU_ID)
        ) AS PRODUCT_KEY
FROM {{ source('raw_data', 'product_lazada') }}