SELECT
    upper(PLATFORM) AS PLATFORM,
    upper(REGION) AS REGION,
    upper(ORDER_ID) AS ORDER_ID,
    upper(PRODUCT_ID) AS PRODUCT_ID,
    upper(SKU_ID) AS SKU_ID,
    CREATED_TIME AS ORDER_AT,
    QUANTITY,
    SALE_PRICE AS ITEM_PRICE,
    PLATFORM_DISCOUNT AS ITEM_PLATFORM_DISCOUNT,
    SELLER_DISCOUNT AS ITEM_SELLER_DISCOUNT,
    SHIPPING_FEE AS ITEM_SHIPPING_FEE,
    SETTLEMENT_AMOUNT AS ITEM_PRICE_AFTER_DISCOUNT,
    upper(STATUS) AS ORDER_STATUS,
    CONCAT_WS(
        '_',
        UPPER(REGION),
        UPPER(PRODUCT_ID),
        UPPER(SKU_ID),
        UPPER(ORDER_ID)
    ) AS ORDER_KEY
FROM  {{ source('raw_data', 'order_tiktok') }}