SELECT
    upper(PLATFORM) AS PLATFORM,
    upper(REGION) AS REGION,
    upper(ORDER_SN) AS ORDER_ID,
    upper(ITEM_ID) AS PRODUCT_ID,
    upper(MODEL_ID) AS SKU_ID,
    ORDER_DATE AS ORDER_AT,
    QUANTITY,
    ITEM_PRICE,
    PLATFORM_DISCOUNT AS ITEM_PLATFORM_DISCOUNT,
    SELLER_DISCOUNT AS ITEM_SELLER_DISCOUNT,
    SHIPPING_FEE AS ITEM_SHIPPING_FEE,
    BUYER_PAYMENT AS ITEM_PRICE_AFTER_DISCOUNT,
    upper(ORDER_STATUS) AS ORDER_STATUS
FROM  {{ source('raw_data', 'order_item_shopee') }}