SELECT
    upper(PLATFORM) AS PLATFORM,
    upper(REGION) AS REGION,
    upper(ORDER_NUMBER) AS ORDER_ID,
    upper(PRODUCT_CODE) AS PRODUCT_ID,
    upper(SELLER_SKU) AS SKU_ID,
    CREATED_AT AS ORDER_AT,
    QTY AS QUANTITY,
    UNIT_PRICE AS ITEM_PRICE,
    SELLER_DISCOUNT AS ITEM_PLATFORM_DISCOUNT,
    VOUCHER_AMOUNT AS ITEM_SELLER_DISCOUNT,
    SHIPPING_COST AS ITEM_SHIPPING_FEE,
    PAID_AMOUNT AS ITEM_PRICE_AFTER_DISCOUNT,
    upper(STATUS) AS ORDER_STATUS
FROM  {{ source('raw_data', 'order_item_lazada') }}