SELECT
    upper(PLATFORM) AS PLATFORM,
    upper(REGION) AS REGION,
    upper(ORDER_NUMBER) AS ORDER_ID,
    CREATED_AT AS ORDER_AT,
    SELLER_NAME AS SHOP_NAME,
    STATUS AS ORDER_STATUS,
    MERCHANDISE_AMOUNT AS TOTAL_AMOUNT,
    VOUCHER_AMOUNT AS TOTAL_DISCOUNT,
    SHIPPING_COST AS SHIPPING_FEE,
    CONCAT_WS(
        '_',
        UPPER(REGION),
        UPPER(PLATFORM),
        UPPER(ORDER_ID)
    ) AS ORDER_KEY
FROM {{ source('raw_data', 'order_lazada') }}